import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import Head from "next/head";
 
import { RouterOutputs, api } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/loading";
import { useState } from "react";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const {user}=useUser();

  const [input,setInput]=useState("");

const ctx=api.useContext();

  const{mutate,isLoading: isPosting}=api.post.create.useMutation({
    onSuccess: () => {
      setInput("");
      ctx.post.getAll.invalidate();
    }
  });
  

  console.log(user);
  if(!user) return null;

  return(
    <div className="flex w-full gap-4">
      <img src={user.profileImageUrl} alt="Profile Image" className="h-24 w-24 rounded-full"/>
      <input placeholder="Type some emojis!" className="grow bg-transparent outline-none"
      type="text" value={input} onChange={(e)=>setInput(e.target.value)}
      disabled={isPosting}/>
      <button onClick={()=>mutate({content:input})}>Post</button>
      </div>
  );
};
 
type PostWithUser =RouterOutputs["post"]["getAll"][number]; 
 
const PostView = (props: PostWithUser) =>{
  const {post,author}=props;
  return (<div key={post.id} className="flex gap-3 border-b border-slate-400 p-8">
    <img src={author.profileImageUrl} alt="Profile Image" className="h-14 w-14 rounded-full"/>
    <div className="flex flex-col">
    <div className="flex gap-1 text-slate-300"><span>{`@${author.username}`}</span>
    <span className="font-thin">{`- ${dayjs(post.createdAt).fromNow()}`}</span></div>
    <span>{post.content}</span></div>    
    </div>);
};  

export default function Home() {

  const user=useUser();
  const{data,isLoading}=api.post.getAll.useQuery();
  
  if(isLoading) return <LoadingPage />;
  if(!data)  return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
      <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
        <div className="flex border-b border-slate400 p-4">
          {!user.isSignedIn && (<div className="flex justify-center"><SignInButton/></div>)}
          {user.isSignedIn && <CreatePostWizard/>}
        </div>
      <div className="flex flex-col">        
        {data.map((fullPost)=>(<PostView{...fullPost} key={fullPost.post.id}/>))} 
      </div>
      </div>
      </main>
    </>
  );
}; 