import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const {user}=useUser();

  console.log(user);
  if(!user) return null;

  return(
    <div className="flex w-full gap-4">
      <img src={user.profileImageUrl} alt="Profile Image" className="h-24 w-24 rounded-full"/>
      <input placeholder="Type some emojis!" className="grow bg-transparent outline-none"/>
    </div>
  );
};

type PostWithUser =RouterOutputs["post"]["getAll"][number];

const PostView = (props: PostWithUser) =>{
  const {post,author}=props;
  return (<div key={post.id} className="border-b border-slate-400 p-8">
    <img src={author.profileImageUrl}/>{post.content}</div>);
};

export default function Home() {

  const user=useUser();
  const{data,isLoading}=api.post.getAll.useQuery();
  
  //if(isLoading) return <div>Loading...</div>;
  //if(!data)  return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
      <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
        <div className="flex border-b border-slate400 p-4">
          {!user.isSignedIn && (<div className="flex justify-center"><SignInButton/></div>)}
          {user.isSignedIn && <CreatePostWizard/>}
        </div>
      <div className="flex flex-col">
        {data?.map((fullPost)=>(<PostView{...fullPost} key={fullPost.post.id}/>))} 
      </div>
      </div>
      </main>
    </>
  );
};
